### ISSUE TITLE
Request: link to rule

### ISSUE THREAD

**Issue by lkrugertogetr** [manuth/TypeScriptESLintPlugin#197]
I'm not sure if it's even possible with AST, but when displaying a rule could it be possible to link to said rule? E.g.: 
![image](https://user-images.githubusercontent.com/86956017/130615008-cb010ab3-3692-43f1-93dc-72297071261e.png)

Unrelated: anyone know how I can disable typescript formatting rules interfering with prettier in vscode?

**Comment by neurolag** [comment]
Hello
Thanks for your interest in my project.
Sadly, this is not possible. As you can see, the API of `vscode`s language-server (https://github.com/Microsoft/vscode-languageserver-node) allows you to pass the name of the error alongside a link to the docs describing the error.

However, this project uses TypeScript's language-server API which currently only allows you to pass a numeric error-code.
A few months ago, I opened an issue some months a go concerning the absence of this feature: https://github.com/microsoft/TypeScript/issues/39009
Sadly, it doesn't look like this feature request is getting taken care of anytime soon, though.

For the question concerning your formatting - you might want to ask said question on StackOverflow or open an issue in Microsoft's `vscode`-repository: https://github.com/microsoft/vscode.
I think you could just set the `typescript.format.enable`-setting to false in order to solve your issue but I really don't know as I don't use Prettier.

**Comment by lkrugertogetr** [comment]
Thank you! I'll try to figure something out with prettier, for now I'll close this.
